import nodemailer from 'nodemailer';
import forgotPassword from './templates/forgot-password';
import passwordChanged from './templates/password-changed';
import welcome from './templates/welcome';
import verificationEmail from './templates/verification-email';
import { environment } from '@/config/env';
import { logError } from '@/utils/logger';

export interface SendEmail {
  to: string;
  template?: string;
  subject?: string;
  variables?: any;
  templateId?: number;
  data?: any;
}

interface MailOptions {
  from: any;
  to: any;
  subject: any;
  html: any;
}

interface SelectTemplate {
  template: string;
  variables?: any;
}

export default async ({ to, template, variables, templateId }: SendEmail) => {
  if (!template) throw new Error('No mail template specified');

  const { subject, template: temp } = await selectTemplate({
    template,
    variables,
  });

  new Promise((resolve, reject) => {
    // create message
    const mailOptions: MailOptions = {
      from: `"${process.env.APP_NAME}" <info@pressmoni.com>`,
      to,
      subject,
      html: temp ?? '<h2>Check the subject </h2>',
    };

    const mailConfig: any = {
      host: environment.mail?.host || 'smtp.mailtrap.io',
      port: environment.mail?.port || 2525,
      auth: {
        user: environment.mail?.username || 'a3d1159bbbe3a6', //generated by Mailtrap
        pass: environment.mail?.password || '2b4668fe2d6a67', //generated by Mailtrap
      },
    };

    if (environment.mail?.host?.includes('gmail'))
      mailConfig['service'] = environment.mail?.host;

    const transporter = nodemailer.createTransport(mailConfig);

    transporter.sendMail(mailOptions, (error, info) => {
      if (error) {
        console.log(error);
        logError('sendEmail %o', { mailOptions, error });
        reject(new Error('try email again later'));
        return;
      }

      resolve(info);
    });
    return;
  });
};

const selectTemplate = async ({ template, variables }: SelectTemplate) => {
  let subject = ``;
  let _template = undefined;
  switch (template) {
    case 'forgot-password':
      subject += `Password Reset`;
      _template = forgotPassword(variables);
      break;
    case 'verification':
      subject += `Email Verification`;
      _template = verificationEmail(variables);
      break;
    case 'password-changed':
      subject += `Password Changed`;
      _template = passwordChanged(variables);
      break;
    case 'welcome':
      subject += `Welcome to Masteringbackend!`;
      _template = welcome(variables);
      break;
    default:
      break;
  }
  return { template: _template, subject };
};
